# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call(`_LogDis_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_LogDis_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_LogDis_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_LogDis_rcpparma_bothproducts`, x)
}

logm_spd_cpp <- function(X) {
    .Call(`_LogDis_logm_spd_cpp`, X)
}

distance_logeuclid_cpp <- function(mats) {
    .Call(`_LogDis_distance_logeuclid_cpp`, mats)
}

distance_to_inverse_logeuclid_cpp <- function(mats) {
    .Call(`_LogDis_distance_to_inverse_logeuclid_cpp`, mats)
}

u2_statistic_rcpp <- function(D, G) {
    .Call(`_LogDis_u2_statistic_rcpp`, D, G)
}

