# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distance_matrix_mv_cpp <- function(X) {
    .Call(`_mvdistmetricskew_distance_matrix_mv_cpp`, X)
}

distance_matrix_to_flip_cpp <- function(X) {
    .Call(`_mvdistmetricskew_distance_matrix_to_flip_cpp`, X)
}

rcpp_hello_world <- function() {
    .Call(`_mvdistmetricskew_rcpp_hello_world`)
}

