// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpparma_hello_world
arma::mat rcpparma_hello_world();
RcppExport SEXP _LogDis_rcpparma_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpparma_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_outerproduct
arma::mat rcpparma_outerproduct(const arma::colvec& x);
RcppExport SEXP _LogDis_rcpparma_outerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_outerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_innerproduct
double rcpparma_innerproduct(const arma::colvec& x);
RcppExport SEXP _LogDis_rcpparma_innerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_innerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_bothproducts
Rcpp::List rcpparma_bothproducts(const arma::colvec& x);
RcppExport SEXP _LogDis_rcpparma_bothproducts(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_bothproducts(x));
    return rcpp_result_gen;
END_RCPP
}
// logm_spd_cpp
arma::mat logm_spd_cpp(const arma::mat& X);
RcppExport SEXP _LogDis_logm_spd_cpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(logm_spd_cpp(X));
    return rcpp_result_gen;
END_RCPP
}
// distance_logeuclid_cpp
NumericMatrix distance_logeuclid_cpp(const arma::cube& mats);
RcppExport SEXP _LogDis_distance_logeuclid_cpp(SEXP matsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type mats(matsSEXP);
    rcpp_result_gen = Rcpp::wrap(distance_logeuclid_cpp(mats));
    return rcpp_result_gen;
END_RCPP
}
// distance_to_inverse_logeuclid_cpp
NumericMatrix distance_to_inverse_logeuclid_cpp(const arma::cube& mats);
RcppExport SEXP _LogDis_distance_to_inverse_logeuclid_cpp(SEXP matsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type mats(matsSEXP);
    rcpp_result_gen = Rcpp::wrap(distance_to_inverse_logeuclid_cpp(mats));
    return rcpp_result_gen;
END_RCPP
}
// u2_statistic_rcpp
double u2_statistic_rcpp(const NumericMatrix& D, const NumericMatrix& G);
RcppExport SEXP _LogDis_u2_statistic_rcpp(SEXP DSEXP, SEXP GSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type G(GSEXP);
    rcpp_result_gen = Rcpp::wrap(u2_statistic_rcpp(D, G));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LogDis_rcpparma_hello_world", (DL_FUNC) &_LogDis_rcpparma_hello_world, 0},
    {"_LogDis_rcpparma_outerproduct", (DL_FUNC) &_LogDis_rcpparma_outerproduct, 1},
    {"_LogDis_rcpparma_innerproduct", (DL_FUNC) &_LogDis_rcpparma_innerproduct, 1},
    {"_LogDis_rcpparma_bothproducts", (DL_FUNC) &_LogDis_rcpparma_bothproducts, 1},
    {"_LogDis_logm_spd_cpp", (DL_FUNC) &_LogDis_logm_spd_cpp, 1},
    {"_LogDis_distance_logeuclid_cpp", (DL_FUNC) &_LogDis_distance_logeuclid_cpp, 1},
    {"_LogDis_distance_to_inverse_logeuclid_cpp", (DL_FUNC) &_LogDis_distance_to_inverse_logeuclid_cpp, 1},
    {"_LogDis_u2_statistic_rcpp", (DL_FUNC) &_LogDis_u2_statistic_rcpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_LogDis(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
