// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// distance_matrix_mv_cpp
NumericMatrix distance_matrix_mv_cpp(const NumericMatrix& X);
RcppExport SEXP _mvdistmetricskew_distance_matrix_mv_cpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(distance_matrix_mv_cpp(X));
    return rcpp_result_gen;
END_RCPP
}
// distance_matrix_to_flip_cpp
NumericMatrix distance_matrix_to_flip_cpp(const NumericMatrix& X);
RcppExport SEXP _mvdistmetricskew_distance_matrix_to_flip_cpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(distance_matrix_to_flip_cpp(X));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _mvdistmetricskew_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mvdistmetricskew_distance_matrix_mv_cpp", (DL_FUNC) &_mvdistmetricskew_distance_matrix_mv_cpp, 1},
    {"_mvdistmetricskew_distance_matrix_to_flip_cpp", (DL_FUNC) &_mvdistmetricskew_distance_matrix_to_flip_cpp, 1},
    {"_mvdistmetricskew_rcpp_hello_world", (DL_FUNC) &_mvdistmetricskew_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_mvdistmetricskew(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
